server:
  port: 8090
  context-path: /luckcatdog/learn

spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/life
      username: root
      password: 123456
  jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mongo_database